# ВЕРСИЯ СКРИПТА v1.764

token = 'MyBotFatherToken'  # ключ api бота
usernames = ['MyTelegramLogin']  # Ваш логин в телеграмме без @, не бота.

routerip = '192.168.1.1'  # ip роутера
browser_port = '8080'  # порт для веб-интерфейса установки ключей
web_auth_user = 'admin'  # логин веб-интерфейса
web_auth_token = ''  # пароль веб-интерфейса; если пусто, вход будет без пароля
web_auth_disabled = False  # True отключает пароль веб-интерфейса, оставляя только LAN + CSRF
fork_repo_owner = 'andruwko73'  # GitHub username вашего форка bypass_keenetic
fork_repo_name = 'bypass_keenetic'  # имя репозитория форка
fork_button_label = 'Fork by andruwko73'  # подпись кнопки установки из вашего форка
app_runtime_mode = 'advanced'  # simple, advanced или web_only
pool_probe_min_available_kb = 190000  # проверка пула не запускает временный xray, если доступной памяти меньше этого порога
pool_probe_pause_available_kb = 125000  # ниже этого порога проверка ставит очередь на паузу до освобождения памяти
pool_probe_slow_available_kb = 190000  # ниже этого порога проверка идёт медленнее, но не останавливается полностью
pool_probe_slow_memory_delay_seconds = 3.0
pool_probe_delay_seconds = 1.5  # пауза между ключами, чтобы полная проверка пула не забивала CPU роутера
pool_probe_cpu_guard_enabled = True
pool_probe_max_cpu_percent = 70.0
pool_probe_cpu_sample_seconds = 0.35
pool_probe_high_cpu_delay_seconds = 5.0
pool_probe_high_cpu_max_wait_seconds = 45.0
pool_probe_max_process_rss_kb = 87040  # рабочий потолок RSS во время проверки пула; после проверки действует restart-порог 70 MB
pool_probe_youtube_profile = 'quick'  # quick для пула, full остаётся для детальной диагностики активного ключа
pool_probe_quality_enabled = True  # короткий download-sample через ключ для оценки YouTube-качества перед применением
pool_probe_quality_download_url = 'https://speed.cloudflare.com/__down?bytes={bytes}'
pool_probe_quality_download_bytes = 1048576
pool_probe_quality_min_available_kb = 170000
pool_probe_quality_max_samples_per_run = 12
pool_probe_quality_download_connect_timeout = 6.0
pool_probe_quality_download_read_timeout = 10.0
pool_probe_quality_stable_latency_ms = 2500
pool_probe_quality_fast_latency_ms = 1500
pool_probe_quality_1600p_min_mbps = 25.0
pool_probe_quality_4k_min_mbps = 45.0
router_health_cache_ttl = 15.0  # быстрый веб-статус памяти/CPU
router_health_dns_cache_ttl = 45.0  # dnsmasq/ipset diagnostics не дергать на каждом обновлении страницы
router_health_ndmc_cache_ttl = 30.0  # ndmc show system тяжелее /proc, держим отдельный TTL
memory_watchdog_enabled = True  # бот сам перезапустит свой сервис, если память Python долго держится выше безопасного порога
memory_watchdog_rss_soft_kb = 87040  # при достижении порога очищаются кэши статуса и запускается gc.collect()
memory_watchdog_rss_limit_kb = 112640  # выше этого RSS бот перезапустится, если сейчас не идёт обновление или проверка пула
memory_watchdog_idle_restart_rss_kb = 71680  # если бот долго держит RSS выше этого уровня в простое, сервис будет мягко перезапущен
memory_watchdog_idle_restart_hold_seconds = 120.0
memory_watchdog_check_interval = 60.0
memory_watchdog_min_uptime_seconds = 300.0
memory_watchdog_restart_cooldown_seconds = 1800.0
memory_post_pool_restart_enabled = True  # после проверки пула бот сам снизит память и перезапустится, если Python RSS остался высоким
memory_post_pool_restart_rss_kb = 71680
memory_post_pool_restart_delay_seconds = 20.0
memory_post_pool_restart_retry_seconds = 30.0
memory_post_pool_restart_max_wait_seconds = 300.0
memory_timeline_enabled = True
memory_timeline_path = '/opt/tmp/bypass_memory_timeline.jsonl'
memory_timeline_interval_seconds = 60.0
memory_timeline_max_events = 240
memory_malloc_trim_enabled = True  # после тяжёлой очистки просит libc вернуть свободные арены памяти системе
memory_malloc_trim_min_rss_kb = 61440
memory_malloc_trim_cooldown_seconds = 20.0
udp_quic_block_shadowsocks_enabled = True  # smart QUIC/UDP 443 fallback for service domains from the Shadowsocks list
udp_quic_block_vmess_enabled = True  # smart QUIC/UDP 443 fallback for service domains from the Vmess list
udp_quic_block_vless_enabled = True  # smart QUIC/UDP 443 fallback for non-YouTube routes
udp_quic_block_vless2_enabled = True  # smart QUIC/UDP 443 fallback for non-YouTube routes
udp_quic_block_trojan_enabled = True  # smart QUIC/UDP 443 fallback for service domains from the Trojan list
youtube_quic_policy = 'auto'  # auto blocks QUIC for routes that contain YouTube; allow permits QUIC; block forces TCP fallback
telegram_udp_policy = 'auto'  # auto/allow keep UDP open for Telegram routes so native calls can use relay/media traffic; block disables it
telegram_call_learning_enabled = True
telegram_call_learning_state_path = '/tmp/bypass_telegram_call_learning.json'
telegram_call_learning_default_duration_seconds = 90
telegram_call_learning_max_duration_seconds = 180
telegram_call_learning_poll_interval_seconds = 1.0
telegram_call_learning_auto_enabled = True
telegram_call_learning_scan_interval_seconds = 5.0
telegram_call_learning_idle_backoff_seconds = 60.0
telegram_call_learning_route_cache_ttl_seconds = 30.0
telegram_call_learning_fast_scan_limit = 3
telegram_call_learning_min_score = 5
telegram_call_learning_min_packets = 2
telegram_call_learning_min_bytes = 240
telegram_call_learning_max_candidates = 20
telegram_call_learning_max_seen_addresses = 512
telegram_call_learning_apply_by_default = True
telegram_call_learning_client_timeout_seconds = 900  # idle kernel window after Telegram signaling from a LAN client
telegram_call_learning_address_timeout_seconds = 14400  # learned call relay/P2P addresses expire automatically
telegram_call_tproxy_enabled = True  # routes Telegram call UDP through TPROXY when KeenOS exposes xt_TPROXY/xt_socket
udp_quic_drift_priority_refresh_cooldown_seconds = 120  # refresh YouTube/Googlevideo ipset drift faster than low-priority service drift
ipset_refresh_command_timeout_seconds = 420  # allow slower low-load ipset refreshes on busy routers
ipv6_bypass_fallback_enabled = True  # для ndnproxy: сбрасывать IPv6 к доменам обхода, чтобы клиенты быстро переходили на IPv4 через прокси
reality_endpoint_overrides = {}  # необязательно: {'server.example.com': '203.0.113.10'} для Reality-доменов с нестабильным DNS-бэкендом
reality_endpoint_repair_enabled = True  # перед сменой Reality-ключа бот пробует рабочие endpoint'ы текущего ключа
reality_endpoint_repair_max_candidates = 6
reality_endpoint_repair_dns_servers = ('1.1.1.1', '8.8.8.8', '9.9.9.9')
auto_failover_startup_hold_seconds = 180  # после рестарта бот не переключает Telegram-ключи, пока Xray и маршруты стабилизируются
youtube_vless2_failover_enabled = True  # YouTube остается на Vless 2: если текущий Vless2 ключ перестал отвечать, бот подберет другой из пула Vless2
auto_failover_consecutive_failures = 3  # switch Telegram key only after repeated confirmed failures
youtube_vless2_failover_grace_seconds = 180
youtube_vless2_failover_poll_seconds = 120
youtube_vless2_failover_switch_cooldown_seconds = 300
youtube_vless2_failover_check_connect_timeout = 6
youtube_vless2_failover_check_read_timeout = 10
youtube_vless2_failover_confirm_retries = 3
youtube_vless2_failover_confirm_delay_seconds = 8.0
youtube_vless2_restart_recheck_enabled = True
youtube_vless2_restart_recheck_cooldown_seconds = 300
youtube_vless2_failover_consecutive_failures = 3
youtube_vless2_hard_failure_recovery_cooldown_seconds = 90
youtube_stream_guard_scan_cache_seconds = 8.0  # reuse recent conntrack scan results to avoid repeated CPU spikes
youtube_stream_guard_failover_hold_seconds = 45  # Если при просмотре YouTube трафик пропал, автозамена Vless2 сможет продолжиться после этой паузы

# следующие настройки могут быть оставлены по умолчанию, но можно будет что-то поменять
localportsh = '1082'  # локальный порт для shadowsocks
localportvmess = '10810'  # локальный порт для vmess
localportvless = '10811'  # локальный порт для vless
localporttrojan = '10829'  # локальный порт для trojan
localportsh_tproxy = '11802'  # UDP TPROXY inbound for Telegram calls through Shadowsocks
localportvmess_tproxy = '11815'  # UDP TPROXY inbound for Telegram calls through VMess
localportvless_tproxy = '11812'  # UDP TPROXY inbound for Telegram calls through Vless
localportvless2_tproxy = '11814'  # UDP TPROXY inbound for Telegram calls through Vless 2
localporttrojan_tproxy = '11829'  # UDP TPROXY inbound for Telegram calls through Trojan
default_proxy_mode = 'none'  # выбор прокси для Telegram API: none, shadowsocks, vmess, vless, vless2, trojan
dnsovertlsport = '40500'  # можно посмотреть номер порта командой "cat /tmp/ndnproxymain.stat"
dnsoverhttpsport = '40508'  # можно посмотреть номер порта командой "cat /tmp/ndnproxymain.stat"
