# Shared route and check presets for the web panel and Telegram bot.

YOUTUBE_CDN_IP_RANGES = [
    '64.233.0.0/16',
    '72.14.0.0/16',
    '74.125.0.0/16',
    '108.177.0.0/16',
    '142.250.0.0/15',
    '172.217.0.0/16',
    '172.253.0.0/16',
    '173.194.0.0/16',
    '209.85.0.0/16',
    '216.58.192.0/18',
]

YOUTUBE_UNBLOCK_ENTRIES = [
    *YOUTUBE_CDN_IP_RANGES,
    'youtube.com',
    'www.youtube.com',
    'm.youtube.com',
    'music.youtube.com',
    'studio.youtube.com',
    'tv.youtube.com',
    'kids.youtube.com',
    'gaming.youtube.com',
    'youtu.be',
    'youtube-nocookie.com',
    'www.youtube-nocookie.com',
    'youtubeeducation.com',
    'www.youtubeeducation.com',
    'youtubei.googleapis.com',
    'youtube.googleapis.com',
    'youtubeembeddedplayer.googleapis.com',
    'youtube-ui.l.google.com',
    'wide-youtube.l.google.com',
    'yt-video-upload.l.google.com',
    'ytimg.com',
    'i.ytimg.com',
    's.ytimg.com',
    'yt3.ggpht.com',
    'yt3.googleusercontent.com',
    'yt4.ggpht.com',
    'ggpht.com',
    'googlevideo.com',
    'redirector.googlevideo.com',
    'video.google.com',
    'jnn-pa.googleapis.com',
    'play-fe.googleapis.com',
    'gvt1.com',
    'gvt2.com',
]

CHATGPT_ROUTE_ENTRIES = [
    'chatgpt.com',
    'ab.chatgpt.com',
    'api.chatgpt.com',
    'chat.openai.com',
    'ws.chatgpt.com',
    'ios.chat.openai.com',
    'android.chat.openai.com',
    'desktop.chat.openai.com',
    'tcr9i.chat.openai.com',
    'api.openai.com',
    'platform.openai.com',
    'auth.openai.com',
    'auth0.openai.com',
    'setup.auth.openai.com',
    'openai.com',
    'cdn.openai.com',
    'cdn.openaimerge.com',
    'openaiassets.blob.core.windows.net',
    'ct.sendgrid.net',
    'oaistatic.com',
    'cdn.oaistatic.com',
    'persistent.oaistatic.com',
    'oaiusercontent.com',
    'files.oaiusercontent.com',
    'images.ctfassets.net',
    'featuregates.org',
    'featureassets.org',
    'statsig.com',
    'statsigapi.net',
    'api.statsig.com',
    'api.statsigcdn.com',
    'events.statsigapi.net',
    'cloudflare-dns.com',
    'intercom.io',
    'intercomcdn.com',
    'js.intercomcdn.com',
    'cdn.workos.com',
    'forwarder.workos.com',
    'images.workoscdn.com',
    'workos.imgix.net',
    'setup.workos.com',
    'challenges.cloudflare.com',
    'gateway.ai.cloudflare.com',
    'js.stripe.com',
    'humb.apple.com',
    'prodregistryv2.org',
    'browser-intake-datadoghq.com',
    'rum.browser-intake-datadoghq.com',
    'o207216.ingest.sentry.io',
    'o33249.ingest.sentry.io',
    'accounts.google.com',
    'google.com',
]

CHATGPT_EDGE_IP_ENTRIES = [
    '8.6.112.6',
    '8.47.69.6',
    '35.190.80.1',
    '64.239.109.65',
    '104.18.32.47',
    '172.64.155.209',
]

CHATGPT_ROUTE_ENTRIES.extend(CHATGPT_EDGE_IP_ENTRIES)

TELEGRAM_SHARED_EDGE_IP_ENTRIES = [
    # Keep this list empty for now: chatgpt.com can resolve to the same
    # Cloudflare edges, and excluding them lets browser QUIC leak directly.
]

CLAUDE_ROUTE_ENTRIES = [
    'claude.ai',
    'claude.com',
    'platform.claude.com',
    'console.anthropic.com',
    'api.anthropic.com',
    'a-api.anthropic.com',
    'a-cdn.anthropic.com',
    'anthropic.com',
    'www.anthropic.com',
    'assets.anthropic.com',
    'statsig.anthropic.com',
    'claudeusercontent.com',
    'cdn.amplitude.com',
    'sr-client-cfg.amplitude.com',
    'cdn.jsdelivr.net',
    'cdnjs.cloudflare.com',
    'unpkg.com',
    'cdn.prod.website-files.com',
    'd3e54v103j8qbb.cloudfront.net',
    '160.79.104.0/23',
]

GEMINI_ROUTE_ENTRIES = [
    'gemini.google.com',
    'bard.google.com',
    'aistudio.google.com',
    'ai.studio',
    'ai.google.dev',
    'generativelanguage.googleapis.com',
    'alkalimakersuite-pa.clients6.google.com',
    'waa-pa.clients6.google.com',
    'accounts.google.com',
    'oauth2.googleapis.com',
    'www.googleapis.com',
    'apis.google.com',
    'www.google.com',
    'ogs.google.com',
    'play.google.com',
    'ssl.gstatic.com',
    'www.gstatic.com',
    'fonts.googleapis.com',
    'fonts.gstatic.com',
    'lh3.googleusercontent.com',
    'lh5.googleusercontent.com',
    'lh3.google.com',
    'maps.gstatic.com',
    'maps.googleapis.com',
    'ogads-pa.clients6.google.com',
    'csp.withgoogle.com',
    'www.googletagmanager.com',
    'www.google-analytics.com',
    'static.doubleclick.net',
    'td.doubleclick.net',
    'googleads.g.doubleclick.net',
    'optimizationguide-pa.googleapis.com',
    'content-autofill.googleapis.com',
    'encrypted-tbn0.gstatic.com',
    'encrypted-tbn1.gstatic.com',
    'encrypted-tbn2.gstatic.com',
    'encrypted-tbn3.gstatic.com',
    'streetviewpixels-pa.googleapis.com',
]

GROK_ROUTE_ENTRIES = [
    'grok.com',
    'x.ai',
    'api.x.ai',
    'x.com',
    'api.x.com',
    'twitter.com',
    'api.twitter.com',
    't.co',
    'twimg.com',
    'pbs.twimg.com',
    'video.twimg.com',
    'abs.twimg.com',
    'ton.twimg.com',
]

COPILOT_ROUTE_ENTRIES = [
    'copilot.microsoft.com',
    'bing.com',
    'www.bing.com',
    'edgeservices.bing.com',
    'sydney.bing.com',
    'login.microsoftonline.com',
    'api.githubcopilot.com',
    'githubcopilot.com',
    'githubcopilotusercontent.com',
    'copilot-proxy.githubusercontent.com',
    'default.exp-external-v8.env.microsoft.com',
]

PERPLEXITY_ROUTE_ENTRIES = [
    'perplexity.ai',
    'www.perplexity.ai',
    'api.perplexity.ai',
]

DEEPSEEK_ROUTE_ENTRIES = [
    'deepseek.com',
    'chat.deepseek.com',
    'api.deepseek.com',
    'platform.deepseek.com',
]

DISCORD_ROUTE_ENTRIES = [
    'dis.gd',
    'discord.co',
    'discord.com',
    'discord.design',
    'discord.dev',
    'discord.gift',
    'discord.gifts',
    'discordapp.com',
    'discordapp.net',
    'discord.gg',
    'discord.media',
    'discord.new',
    'discord.store',
    'discord.tools',
    'gateway.discord.gg',
    'cdn.discordapp.com',
    'cdn.discordapp.net',
    'media.discordapp.net',
    'images-ext-1.discordapp.net',
    'stable.dl2.discordapp.net',
    'discord-activities.com',
    'discordactivities.com',
    'discord-attachments-uploads-prd.storage.googleapis.com',
    'discordmerch.com',
    'discordpartygames.com',
    'discordsays.com',
    'discordstatus.com',
]

META_AI_ROUTE_ENTRIES = [
    'meta.ai',
    'www.meta.ai',
    'ai.meta.com',
    'meta.com',
]

INSTAGRAM_ROUTE_ENTRIES = [
    'instagram.com',
    'www.instagram.com',
    'cdninstagram.com',
    'ig.me',
]

FACEBOOK_ROUTE_ENTRIES = [
    'facebook.com',
    'www.facebook.com',
    'graph.facebook.com',
    'fbcdn.net',
    'facebook.net',
    'fb.com',
    'fbsbx.com',
    'cdnfacebook.com',
]

META_PLATFORM_ROUTE_ENTRIES = [
    *META_AI_ROUTE_ENTRIES,
    *INSTAGRAM_ROUTE_ENTRIES,
    *FACEBOOK_ROUTE_ENTRIES,
    'internalfb.com',
    'threads.net',
    'wa.me',
    'whatsapp.biz',
    'whatsapp.com',
    'whatsapp.net',
    'oculus.com',
]

CHROME_REMOTE_DESKTOP_SIGNAL_IP_ENTRIES = [
    '64.233.161.95',
    '64.233.161.189',
    '64.233.162.95',
    '64.233.162.188',
    '64.233.163.95',
    '64.233.164.95',
    '64.233.165.95',
    '74.125.131.95',
    '74.125.131.100',
    '74.125.131.101',
    '74.125.131.102',
    '74.125.131.113',
    '74.125.131.138',
    '74.125.131.139',
    '74.125.205.95',
    '108.177.14.95',
    '108.177.125.188',
    '142.250.101.188',
    '142.250.150.95',
    '142.251.1.95',
    '172.217.78.188',
    '172.217.221.188',
    '172.253.152.95',
    '172.253.158.188',
    '173.194.43.188',
    '173.194.73.95',
    '173.194.221.95',
    '173.194.222.95',
    '192.178.128.188',
    '209.85.233.95',
    '216.239.32.223',
    '216.239.34.223',
    '216.239.36.223',
    '216.239.38.223',
]

CHROME_REMOTE_DESKTOP_ROUTE_ENTRIES = [
    'remotedesktop.google.com',
    'remotedesktop-pa.googleapis.com',
    'instantmessaging-pa.googleapis.com',
    'instantmessaging-pa.clients6.google.com',
    'www.gstatic.com',
    'ssl.gstatic.com',
    'oauth2.googleapis.com',
    'www.googleapis.com',
    'accounts.google.com',
    'apis.google.com',
    'clients2.google.com',
    'clients3.google.com',
    'clients4.google.com',
    'clients6.google.com',
    'mtalk.google.com',
    'alt1-mtalk.google.com',
    'alt2-mtalk.google.com',
    'alt3-mtalk.google.com',
    'alt4-mtalk.google.com',
    'alt5-mtalk.google.com',
    'alt6-mtalk.google.com',
    'alt7-mtalk.google.com',
    'alt8-mtalk.google.com',
    'chromoting-client.talkgadget.google.com',
    'talkgadget.google.com',
    '74.125.247.128',
    *CHROME_REMOTE_DESKTOP_SIGNAL_IP_ENTRIES,
]

CUSTOM_CHECK_PRESETS = [
    {
        'id': 'chatgpt_services',
        'label': 'ChatGPT / Codex',
        'url': 'https://chatgpt.com',
        'urls': [
            'https://api.openai.com/v1/models',
        ],
        'routes': CHATGPT_ROUTE_ENTRIES,
        'badge': 'GPT',
        'icon': 'chatgpt',
    },
    {
        'id': 'claude',
        'label': 'Claude',
        'url': 'https://claude.ai',
        'urls': [
            'https://api.anthropic.com/v1/models',
        ],
        'routes': CLAUDE_ROUTE_ENTRIES,
        'badge': 'CL',
        'icon': 'claude',
    },
    {
        'id': 'gemini',
        'label': 'Gemini',
        'url': 'https://gemini.google.com',
        'urls': [
            'https://gemini.google.com',
            'https://aistudio.google.com',
            'https://ai.google.dev',
            'https://generativelanguage.googleapis.com',
        ],
        'routes': GEMINI_ROUTE_ENTRIES,
        'badge': 'GM',
        'icon': 'gemini',
    },
    {
        'id': 'copilot',
        'label': 'Copilot',
        'url': 'https://copilot.microsoft.com',
        'routes': COPILOT_ROUTE_ENTRIES,
        'badge': 'CP',
        'icon': 'copilot',
    },
    {
        'id': 'perplexity',
        'label': 'Perplexity',
        'url': 'https://www.perplexity.ai',
        'routes': PERPLEXITY_ROUTE_ENTRIES,
        'badge': 'PX',
        'icon': 'perplexity',
    },
    {
        'id': 'grok',
        'label': 'Grok',
        'url': 'https://grok.com',
        'urls': ['https://grok.com', 'https://x.ai', 'https://x.com', 'https://twitter.com'],
        'routes': GROK_ROUTE_ENTRIES,
        'badge': 'GX',
        'icon': 'grok',
    },
    {
        'id': 'deepseek',
        'label': 'DeepSeek',
        'url': 'https://chat.deepseek.com',
        'urls': ['https://chat.deepseek.com', 'https://api.deepseek.com'],
        'routes': DEEPSEEK_ROUTE_ENTRIES,
        'badge': 'DS',
        'icon': 'deepseek',
    },
    {
        'id': 'discord',
        'label': 'Discord',
        'url': 'https://discord.com',
        'urls': [
            'https://discord.com/api/v10/gateway',
        ],
        'routes': DISCORD_ROUTE_ENTRIES,
        'badge': 'DC',
        'icon': 'discord',
    },
    {
        'id': 'chrome_remote_desktop',
        'label': 'Chrome Remote Desktop',
        'url': 'https://remotedesktop.google.com',
        'urls': [
            'https://remotedesktop.google.com',
            'https://remotedesktop-pa.googleapis.com',
            'https://instantmessaging-pa.googleapis.com',
        ],
        'routes': CHROME_REMOTE_DESKTOP_ROUTE_ENTRIES,
        'badge': 'CRD',
    },
    {
        'id': 'meta_ai',
        'label': 'Meta AI',
        'url': 'https://www.meta.ai',
        'urls': ['https://www.meta.ai', 'https://ai.meta.com'],
        'routes': META_AI_ROUTE_ENTRIES,
        'badge': 'MA',
        'icon': 'meta',
    },
    {
        'id': 'instagram',
        'label': 'Instagram',
        'url': 'https://www.instagram.com',
        'routes': INSTAGRAM_ROUTE_ENTRIES,
        'badge': 'IG',
        'icon': 'instagram',
    },
    {
        'id': 'facebook',
        'label': 'Facebook',
        'url': 'https://www.facebook.com',
        'urls': ['https://www.facebook.com', 'https://graph.facebook.com'],
        'routes': FACEBOOK_ROUTE_ENTRIES,
        'badge': 'FB',
        'icon': 'facebook',
    },
]

CONNECTIVITY_CHECK_DOMAINS = [
    'full:connectivitycheck.gstatic.com',
    'full:connectivitycheck.android.com',
    'full:clients3.google.com',
    'full:clients4.google.com',
    'full:www.google.com',
]

TELEGRAM_UNBLOCK_ENTRIES = [
    '91.108.56.0/22',
    '91.108.4.0/22',
    '91.108.8.0/22',
    '91.108.16.0/22',
    '91.108.12.0/22',
    '149.154.160.0/20',
    '91.105.192.0/23',
    '91.108.20.0/22',
    '185.76.151.0/24',
    '5.28.192.0/21',
    '95.161.64.0/20',
    'api.telegram.org',
    'web.telegram.org',
    'my.telegram.org',
    'core.telegram.org',
    'oauth.telegram.org',
    'widgets.telegram.org',
    't.me',
    'tx.me',
    'telegra.ph',
    'graph.org',
    'telegram.org',
    'telegram.me',
    'telegram.dog',
    'telegram-cdn.org',
    'telegramapp.org',
    'telegramdownload.com',
    'cdn-telegram.org',
    'telegram.ai',
    'telegram.asia',
    'telegram.biz',
    'telegram.cloud',
    'telegram.cn',
    'telegram.co',
    'telegram.com',
    'telegram.de',
    'telegram.dev',
    'telegram.eu',
    'telegram.fr',
    'telegram.host',
    'telegram.in',
    'telegram.info',
    'telegram.io',
    'telegram.jp',
    'telegram.net',
    'telegram.qa',
    'telegram.ru',
    'telegram.services',
    'telegram.solutions',
    'telegram.space',
    'telegram.team',
    'telegram.tech',
    'telegram.uk',
    'telegram.us',
    'telegram.website',
    'telegram.xyz',
    'telesco.pe',
    'comments.app',
    'contest.com',
    'fragment.com',
    'quiz.directory',
    'walletbot.me',
    'toncenter.walletbot.me',
    'p2p.walletbot.me',
    'wallet.tg',
    'help.wallet.tg',
    'wallet.helpscoutdocs.com',
    'ston.fi',
    'app.ston.fi',
    'api.ston.fi',
    'tonapi.io',
    'bridge.tonapi.io',
    'toncenter.com',
    'tonkeeper.com',
    'app.tonkeeper.com',
    'tonconsole.com',
    'tonapps.group',
    'tonviewer.com',
    'tonscan.org',
    'getgems.io',
    'dedust.io',
    'api.dedust.io',
    'ton-connect.github.io',
    'raw.githubusercontent.com',
    'mytonwallet.io',
    'mytonwallet.app',
    'tonhub.com',
    'connect.tonhubapi.com',
    'openmask.app',
    'openmask.icu',
    't-bank-app.ru',
    'id.t-bank-app.ru',
    'acdn.tinkoff.ru',
    'tinkoff.ru',
    'tbank.ru',
    'www.tbank.ru',
    '194.221.250.50',
    '23.216.134.15',
    '104.21.72.109',
    '151.101.129.91',
    '151.101.193.91',
    '212.188.32.34',
    '18.165.122.105',
    '13.33.235.84',
    '104.103.64.59',
    '80.239.150.25',
    '54.76.177.33',
    '104.17.79.30',
    '3.248.1.23',
    '13.33.235.64',
    'internal.api.vk.ru',
    'queuev4.vk.ru',
    'vk-analytics.ru',
    'tracker-api.vk-analytics.ru',
    'ip4.tracker-api.vk-analytics.ru',
    'ts.tracker-api.vk-analytics.ru',
    '87.240.137.130',
    '95.213.56.4',
    '90.156.232.26',
    'tg.dev',
    'tg.org',
    'tgram.org',
    'tdesktop.com',
    'teleg.xyz',
    'telega.one',
    'ton.org',
    'usercontent.dev',
]

SERVICE_LIST_SOURCES = {
    'chatgpt_services': {
        'label': 'ChatGPT / Codex',
        'aliases': ['chatgpt', 'codex', 'openai', 'gpt', 'chatgpt codex'],
        'url': '',
        'entries': CHATGPT_ROUTE_ENTRIES,
        'udp_quic': True,
        'udp_quic_exclude': TELEGRAM_SHARED_EDGE_IP_ENTRIES,
    },
    'claude': {
        'label': 'Claude',
        'aliases': ['claude', 'anthropic', 'cloude'],
        'url': '',
        'entries': CLAUDE_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'gemini': {
        'label': 'Gemini',
        'aliases': ['gemini', 'google ai', 'google ai studio', 'aistudio', 'bard'],
        'url': '',
        'entries': GEMINI_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'copilot': {
        'label': 'Copilot',
        'aliases': ['copilot', 'microsoft copilot', 'github copilot'],
        'url': '',
        'entries': COPILOT_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'perplexity': {
        'label': 'Perplexity',
        'aliases': ['perplexity', 'pplx'],
        'url': '',
        'entries': PERPLEXITY_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'grok': {
        'label': 'Grok',
        'aliases': ['grok', 'xai', 'x ai'],
        'url': '',
        'entries': GROK_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'deepseek': {
        'label': 'DeepSeek',
        'aliases': ['deepseek', 'deep seek'],
        'url': '',
        'entries': DEEPSEEK_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'youtube': {
        'label': 'YouTube',
        'aliases': ['youtube', 'yt', 'ютуб'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/youtube.lst',
        'entries': YOUTUBE_UNBLOCK_ENTRIES,
        'udp_quic': True,
    },
    'telegram': {
        'label': 'Telegram',
        'aliases': ['telegram', 'tg', 'телеграм', 'телега'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/telegram.lst',
        'entries': TELEGRAM_UNBLOCK_ENTRIES,
        'udp_quic': True,
    },
    'meta': {
        'label': 'Instagram / Meta',
        'aliases': ['meta', 'instagram', 'insta', 'facebook', 'whatsapp', 'threads', 'инстаграм'],
        'url': '',
        'entries': META_PLATFORM_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'discord': {
        'label': 'Discord',
        'aliases': ['discord', 'дискорд'],
        'url': '',
        'entries': DISCORD_ROUTE_ENTRIES,
    },
    'chrome_remote_desktop': {
        'label': 'Chrome Remote Desktop',
        'aliases': ['chrome remote desktop', 'crd', 'chromoting', 'remote desktop', 'удаленный рабочий стол chrome'],
        'url': '',
        'entries': CHROME_REMOTE_DESKTOP_ROUTE_ENTRIES,
    },
    'meta_ai': {
        'label': 'Meta AI',
        'aliases': ['meta', 'meta ai', 'metaai'],
        'url': '',
        'entries': META_AI_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'instagram': {
        'label': 'Instagram',
        'aliases': ['instagram', 'insta'],
        'url': '',
        'entries': INSTAGRAM_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'facebook': {
        'label': 'Facebook',
        'aliases': ['facebook', 'fb'],
        'url': '',
        'entries': FACEBOOK_ROUTE_ENTRIES,
        'udp_quic': True,
    },
    'tiktok': {
        'label': 'TikTok',
        'aliases': ['tiktok', 'tik-tok', 'тик ток', 'тикток'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/tiktok.lst',
    },
    'twitter': {
        'label': 'X / Twitter',
        'aliases': ['twitter', 'x', 'твиттер'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/twitter.lst',
    },
}

YOUTUBE_UDP_QUIC_EXTRA_ENTRIES = [
    'yt.be',
    'youtubekids.com',
]


def _dedupe_policy_entries(values):
    result = []
    seen = set()
    for value in values or []:
        entry = str(value or '').strip().lower()
        if not entry or entry.startswith('#') or entry in seen:
            continue
        seen.add(entry)
        result.append(entry)
    return result


def udp_quic_policy_entries(service_sources=None):
    sources = service_sources or SERVICE_LIST_SOURCES
    entries = []
    for source in sources.values():
        if source.get('udp_quic'):
            excluded = {
                str(value or '').strip().lower()
                for value in source.get('udp_quic_exclude') or []
            }
            entries.extend(
                entry for entry in source.get('entries') or []
                if str(entry or '').strip().lower() not in excluded
            )
    entries.extend(YOUTUBE_UDP_QUIC_EXTRA_ENTRIES)
    return _dedupe_policy_entries(entries)


def udp_quic_exclude_entries(service_sources=None):
    sources = service_sources or SERVICE_LIST_SOURCES
    entries = []
    for source in sources.values():
        entries.extend(source.get('udp_quic_exclude') or [])
    return _dedupe_policy_entries(entries)


UDP_QUIC_ROUTE_ENTRIES = udp_quic_policy_entries()
UDP_QUIC_EXCLUDE_ENTRIES = udp_quic_exclude_entries()
