# Shared route and check presets for the web panel and Telegram bot.

YOUTUBE_CDN_IP_RANGES = [
    '64.233.0.0/16',
    '72.14.0.0/16',
    '74.125.0.0/16',
    '108.177.0.0/16',
    '142.250.0.0/15',
    '172.217.0.0/16',
    '172.253.0.0/16',
    '173.194.0.0/16',
    '209.85.0.0/16',
    '216.58.192.0/18',
]

YOUTUBE_UNBLOCK_ENTRIES = [
    *YOUTUBE_CDN_IP_RANGES,
    'youtube.com',
    'www.youtube.com',
    'm.youtube.com',
    'music.youtube.com',
    'studio.youtube.com',
    'tv.youtube.com',
    'kids.youtube.com',
    'gaming.youtube.com',
    'youtu.be',
    'youtube-nocookie.com',
    'www.youtube-nocookie.com',
    'youtubeeducation.com',
    'www.youtubeeducation.com',
    'youtubei.googleapis.com',
    'youtube.googleapis.com',
    'youtubeembeddedplayer.googleapis.com',
    'youtube-ui.l.google.com',
    'wide-youtube.l.google.com',
    'yt-video-upload.l.google.com',
    'ytimg.com',
    'i.ytimg.com',
    's.ytimg.com',
    'yt3.ggpht.com',
    'yt3.googleusercontent.com',
    'yt4.ggpht.com',
    'ggpht.com',
    'googlevideo.com',
    'redirector.googlevideo.com',
    'video.google.com',
    'jnn-pa.googleapis.com',
    'play-fe.googleapis.com',
    'gvt1.com',
    'gvt2.com',
]

CHATGPT_ROUTE_ENTRIES = [
    'chatgpt.com',
    'ab.chatgpt.com',
    'api.chatgpt.com',
    'chat.openai.com',
    'ws.chatgpt.com',
    'ios.chat.openai.com',
    'android.chat.openai.com',
    'desktop.chat.openai.com',
    'tcr9i.chat.openai.com',
    'api.openai.com',
    'platform.openai.com',
    'auth.openai.com',
    'auth0.openai.com',
    'setup.auth.openai.com',
    'openai.com',
    'cdn.openai.com',
    'cdn.openaimerge.com',
    'ct.sendgrid.net',
    'oaistatic.com',
    'cdn.oaistatic.com',
    'oaiusercontent.com',
    'files.oaiusercontent.com',
    'featuregates.org',
    'featureassets.org',
    'statsig.com',
    'api.statsig.com',
    'events.statsigapi.net',
    'intercom.io',
    'intercomcdn.com',
    'js.intercomcdn.com',
    'cdn.workos.com',
    'forwarder.workos.com',
    'images.workoscdn.com',
    'setup.workos.com',
    'challenges.cloudflare.com',
    'gateway.ai.cloudflare.com',
    'js.stripe.com',
    'prodregistryv2.org',
    'browser-intake-datadoghq.com',
    'rum.browser-intake-datadoghq.com',
    'o207216.ingest.sentry.io',
    'o33249.ingest.sentry.io',
]

CHATGPT_EDGE_IP_ENTRIES = [
    '8.6.112.6',
    '8.47.69.6',
    '35.190.80.1',
    '64.239.109.65',
    '104.18.32.47',
    '172.64.155.209',
]

CHATGPT_ROUTE_ENTRIES.extend(CHATGPT_EDGE_IP_ENTRIES)

CLAUDE_ROUTE_ENTRIES = [
    'claude.ai',
    'claude.com',
    'platform.claude.com',
    'api.anthropic.com',
    'console.anthropic.com',
    'anthropic.com',
    'www.anthropic.com',
    'statsig.anthropic.com',
]

GROK_ROUTE_ENTRIES = [
    'grok.com',
    'x.ai',
    'x.com',
    'api.x.com',
    'twitter.com',
    'api.twitter.com',
    't.co',
    'twimg.com',
    'pbs.twimg.com',
    'video.twimg.com',
    'abs.twimg.com',
    'ton.twimg.com',
]

DISCORD_ROUTE_ENTRIES = [
    'discord.com',
    'discordapp.com',
    'discord.gg',
    'gateway.discord.gg',
    'cdn.discordapp.com',
    'cdn.discordapp.net',
    'media.discordapp.net',
    'images-ext-1.discordapp.net',
]

CHROME_REMOTE_DESKTOP_SIGNAL_IP_ENTRIES = [
    '64.233.161.95',
    '64.233.161.189',
    '64.233.162.95',
    '64.233.162.188',
    '64.233.163.95',
    '64.233.164.95',
    '64.233.165.95',
    '74.125.131.95',
    '74.125.131.100',
    '74.125.131.101',
    '74.125.131.102',
    '74.125.131.113',
    '74.125.131.138',
    '74.125.131.139',
    '74.125.205.95',
    '108.177.14.95',
    '108.177.125.188',
    '142.250.101.188',
    '142.250.150.95',
    '142.251.1.95',
    '172.217.78.188',
    '172.217.221.188',
    '172.253.152.95',
    '172.253.158.188',
    '173.194.43.188',
    '173.194.73.95',
    '173.194.221.95',
    '173.194.222.95',
    '192.178.128.188',
    '209.85.233.95',
    '216.239.32.223',
    '216.239.34.223',
    '216.239.36.223',
    '216.239.38.223',
]

CHROME_REMOTE_DESKTOP_ROUTE_ENTRIES = [
    'remotedesktop.google.com',
    'remotedesktop-pa.googleapis.com',
    'instantmessaging-pa.googleapis.com',
    'instantmessaging-pa.clients6.google.com',
    'www.gstatic.com',
    'ssl.gstatic.com',
    'oauth2.googleapis.com',
    'www.googleapis.com',
    'accounts.google.com',
    'apis.google.com',
    'clients2.google.com',
    'clients3.google.com',
    'clients4.google.com',
    'clients6.google.com',
    'mtalk.google.com',
    'alt1-mtalk.google.com',
    'alt2-mtalk.google.com',
    'alt3-mtalk.google.com',
    'alt4-mtalk.google.com',
    'alt5-mtalk.google.com',
    'alt6-mtalk.google.com',
    'alt7-mtalk.google.com',
    'alt8-mtalk.google.com',
    'chromoting-client.talkgadget.google.com',
    'talkgadget.google.com',
    '74.125.247.128',
    *CHROME_REMOTE_DESKTOP_SIGNAL_IP_ENTRIES,
]

CUSTOM_CHECK_PRESETS = [
    {
        'id': 'chatgpt_services',
        'label': 'ChatGPT / Codex',
        'url': 'https://chatgpt.com',
        'urls': [
            'https://chatgpt.com',
            'https://chatgpt.com/codex',
            'https://api.openai.com',
            'https://platform.openai.com',
        ],
        'routes': CHATGPT_ROUTE_ENTRIES,
        'badge': 'GPT',
        'icon': 'chatgpt',
    },
    {
        'id': 'claude',
        'label': 'Claude',
        'url': 'https://claude.ai',
        'urls': ['https://claude.ai', 'https://api.anthropic.com'],
        'routes': CLAUDE_ROUTE_ENTRIES,
        'badge': 'CL',
        'icon': 'claude',
    },
    {
        'id': 'gemini',
        'label': 'Gemini',
        'url': 'https://gemini.google.com',
        'urls': ['https://gemini.google.com', 'https://generativelanguage.googleapis.com'],
        'routes': ['gemini.google.com', 'generativelanguage.googleapis.com', 'ai.google.dev', 'aistudio.google.com'],
        'badge': 'GM',
        'icon': 'gemini',
    },
    {
        'id': 'copilot',
        'label': 'Copilot',
        'url': 'https://copilot.microsoft.com',
        'routes': ['copilot.microsoft.com', 'bing.com', 'www.bing.com', 'edgeservices.bing.com', 'sydney.bing.com'],
        'badge': 'CP',
        'icon': 'copilot',
    },
    {
        'id': 'perplexity',
        'label': 'Perplexity',
        'url': 'https://www.perplexity.ai',
        'routes': ['perplexity.ai', 'www.perplexity.ai', 'api.perplexity.ai'],
        'badge': 'PX',
        'icon': 'perplexity',
    },
    {
        'id': 'grok',
        'label': 'Grok',
        'url': 'https://grok.com',
        'urls': ['https://grok.com', 'https://x.ai', 'https://x.com', 'https://twitter.com'],
        'routes': GROK_ROUTE_ENTRIES,
        'badge': 'GX',
        'icon': 'grok',
    },
    {
        'id': 'deepseek',
        'label': 'DeepSeek',
        'url': 'https://chat.deepseek.com',
        'urls': ['https://chat.deepseek.com', 'https://api.deepseek.com'],
        'routes': ['deepseek.com', 'chat.deepseek.com', 'api.deepseek.com'],
        'badge': 'DS',
        'icon': 'deepseek',
    },
    {
        'id': 'discord',
        'label': 'Discord',
        'url': 'https://discord.com',
        'urls': [
            'https://discord.com',
            'https://discordapp.com',
            'https://gateway.discord.gg',
            'https://cdn.discordapp.com',
        ],
        'routes': DISCORD_ROUTE_ENTRIES,
        'badge': 'DC',
        'icon': 'discord',
    },
    {
        'id': 'chrome_remote_desktop',
        'label': 'Chrome Remote Desktop',
        'url': 'https://remotedesktop.google.com',
        'urls': [
            'https://remotedesktop.google.com',
            'https://remotedesktop-pa.googleapis.com',
            'https://instantmessaging-pa.googleapis.com',
        ],
        'routes': CHROME_REMOTE_DESKTOP_ROUTE_ENTRIES,
        'badge': 'CRD',
    },
    {
        'id': 'meta_ai',
        'label': 'Meta AI',
        'url': 'https://www.meta.ai',
        'urls': ['https://www.meta.ai', 'https://ai.meta.com'],
        'routes': ['meta.ai', 'www.meta.ai', 'ai.meta.com', 'meta.com'],
        'badge': 'MA',
        'icon': 'meta',
    },
    {
        'id': 'instagram',
        'label': 'Instagram',
        'url': 'https://www.instagram.com',
        'routes': ['instagram.com', 'www.instagram.com', 'cdninstagram.com'],
        'badge': 'IG',
        'icon': 'instagram',
    },
    {
        'id': 'facebook',
        'label': 'Facebook',
        'url': 'https://www.facebook.com',
        'urls': ['https://www.facebook.com', 'https://graph.facebook.com'],
        'routes': ['facebook.com', 'www.facebook.com', 'graph.facebook.com', 'fbcdn.net'],
        'badge': 'FB',
        'icon': 'facebook',
    },
]

CONNECTIVITY_CHECK_DOMAINS = [
    'full:connectivitycheck.gstatic.com',
    'full:connectivitycheck.android.com',
    'full:clients3.google.com',
    'full:clients4.google.com',
    'full:www.google.com',
]

TELEGRAM_UNBLOCK_ENTRIES = [
    '91.108.56.0/22',
    '91.108.4.0/22',
    '91.108.8.0/22',
    '91.108.16.0/22',
    '91.108.12.0/22',
    '149.154.160.0/20',
    '91.105.192.0/23',
    '91.108.20.0/22',
    '185.76.151.0/24',
    '5.28.192.0/21',
    '95.161.64.0/20',
    'api.telegram.org',
    'web.telegram.org',
    'my.telegram.org',
    't.me',
    'tx.me',
    'telegra.ph',
    'graph.org',
    'telegram.org',
    'telegram.me',
    'telegram.dog',
    'telegram-cdn.org',
    'telegramapp.org',
    'telegramdownload.com',
    'cdn-telegram.org',
    'telegram.ai',
    'telegram.asia',
    'telegram.biz',
    'telegram.cloud',
    'telegram.cn',
    'telegram.co',
    'telegram.com',
    'telegram.de',
    'telegram.dev',
    'telegram.eu',
    'telegram.fr',
    'telegram.host',
    'telegram.in',
    'telegram.info',
    'telegram.io',
    'telegram.jp',
    'telegram.net',
    'telegram.qa',
    'telegram.ru',
    'telegram.services',
    'telegram.solutions',
    'telegram.space',
    'telegram.team',
    'telegram.tech',
    'telegram.uk',
    'telegram.us',
    'telegram.website',
    'telegram.xyz',
    'telesco.pe',
    'comments.app',
    'contest.com',
    'fragment.com',
    'quiz.directory',
    'tg.dev',
    'tg.org',
    'tgram.org',
    'tdesktop.com',
    'teleg.xyz',
    'telega.one',
]

SERVICE_LIST_SOURCES = {
    'chatgpt_services': {
        'label': 'ChatGPT / Codex',
        'aliases': ['chatgpt', 'codex', 'openai', 'gpt', 'chatgpt codex'],
        'url': '',
        'entries': CHATGPT_ROUTE_ENTRIES,
    },
    'youtube': {
        'label': 'YouTube',
        'aliases': ['youtube', 'yt', 'ютуб'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/youtube.lst',
        'entries': YOUTUBE_UNBLOCK_ENTRIES,
    },
    'telegram': {
        'label': 'Telegram',
        'aliases': ['telegram', 'tg', 'телеграм', 'телега'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/telegram.lst',
        'entries': TELEGRAM_UNBLOCK_ENTRIES,
    },
    'meta': {
        'label': 'Instagram / Meta',
        'aliases': ['meta', 'instagram', 'insta', 'facebook', 'whatsapp', 'threads', 'инстаграм'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/meta.lst',
    },
    'discord': {
        'label': 'Discord',
        'aliases': ['discord', 'дискорд'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/discord.lst',
    },
    'chrome_remote_desktop': {
        'label': 'Chrome Remote Desktop',
        'aliases': ['chrome remote desktop', 'crd', 'chromoting', 'remote desktop', 'удаленный рабочий стол chrome'],
        'url': '',
        'entries': CHROME_REMOTE_DESKTOP_ROUTE_ENTRIES,
    },
    'tiktok': {
        'label': 'TikTok',
        'aliases': ['tiktok', 'tik-tok', 'тик ток', 'тикток'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/tiktok.lst',
    },
    'twitter': {
        'label': 'X / Twitter',
        'aliases': ['twitter', 'x', 'твиттер'],
        'url': 'https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/twitter.lst',
    },
}
